version: '3.8'

services:
  # Продакшн версия
  new-year-cards:
    build: .
    ports:
      - "3000:3000"
    container_name: new-year-cards-app
    restart: unless-stopped

  # Версия для разработки с Vite
  new-year-cards-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    container_name: new-year-cards-dev
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true